import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,Shield,Trophy,ChevronRight,Medal,History,Users,BarChart3}from'lucide-react';
import d from'./data.json';import'./styles.css';
const names={ARI:'Arizona Cardinals',ATL:'Atlanta Falcons',BAL:'Baltimore Ravens',BUF:'Buffalo Bills',CAR:'Carolina Panthers',CHI:'Chicago Bears',CIN:'Cincinnati Bengals',CLE:'Cleveland Browns',DAL:'Dallas Cowboys',DEN:'Denver Broncos',DET:'Detroit Lions',GB:'Green Bay Packers',HOU:'Houston Texans',IND:'Indianapolis Colts',JAC:'Jacksonville Jaguars',KC:'Kansas City Chiefs',LAC:'Los Angeles Chargers',LAR:'Los Angeles Rams',LV:'Las Vegas Raiders',MIA:'Miami Dolphins',MIN:'Minnesota Vikings',NE:'New England Patriots',NO:'New Orleans Saints',NYG:'New York Giants',NYJ:'New York Jets',PHI:'Philadelphia Eagles',PIT:'Pittsburgh Steelers',SEA:'Seattle Seahawks',SF:'San Francisco 49ers',TB:'Tampa Bay Buccaneers',TEN:'Tennessee Titans',WAS:'Washington Commanders'};
const aliases={JAC:'jax',WAS:'wsh'};const logo=t=>`https://a.espncdn.com/i/teamlogos/nfl/500/${aliases[t]||String(t).toLowerCase()}.png`;
const fullToAbbr=Object.fromEntries(Object.entries(names).map(([k,v])=>[v,k]));
const teamCode=n=>fullToAbbr[n]||Object.keys(names).find(k=>n?.includes(names[k])||names[k]?.includes(n))||({"Seattle Seahawks":'SEA',"Baltimore Ravens":'BAL',"Philadelphia Eagles":'PHI',"Indianapolis Colts":'IND',"Atlanta Falcons":'ATL',"Las Vegas Raiders":'LV'}[n]);
const fmt=v=>typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:1}):v;
function Logo({team,size=48}){const[bad,setBad]=useState(false);return bad?<b className="badge" style={{width:size,height:size}}>{team||'NFL'}</b>:<img className="logo" src={logo(team)} onError={()=>setBad(true)} style={{width:size,height:size}} alt=""/>}
function Header({go}){return <header><button className="brand" onClick={()=>go('dashboard')}><Shield/><span>Madden Dynasty Franchise</span></button><nav><button onClick={()=>go('dashboard')}>Dashboard</button><button onClick={()=>go('franchises')}>Franchises</button><button onClick={()=>go('one')}>One Team</button><button onClick={()=>go('all')}>All-Time</button></nav></header>}
function Dashboard({go}){const years=d.history.slice().sort((a,b)=>b.year-a.year);const[selected,setSelected]=useState(years[0]?.year);const s=years.find(x=>x.year===selected);return <><section className="mast"><span>MADDEN DYNASTY FRANCHISE</span><h1>Madden Dynasty Franchise</h1></section><div className="quick"><button onClick={()=>go('franchises')}><Users/><span><b>32 Franchises</b><small>Career and single-season records</small></span><ChevronRight/></button><button onClick={()=>go('one')}><Medal/><span><b>One Team Leaders</b><small>Career production for one franchise</small></span><ChevronRight/></button><button onClick={()=>go('all')}><BarChart3/><span><b>All-Time Leaders</b><small>Workbook-wide career records</small></span><ChevronRight/></button></div><section className="historyHead"><div><span>LEAGUE HISTORY</span><h2>Season archive</h2></div><History/></section><div className="years">{years.map(x=><button key={x.year} className={selected===x.year?'on':''} onClick={()=>setSelected(x.year)}>{x.year}</button>)}</div>{s&&<Season s={s}/>}</>}
function Season({s}){const c=teamCode(s.champion);return <article className="season"><div className="champion"><div><span>{s.year} CHAMPION</span><h2>{s.champion}</h2><p>{s.superBowl}</p></div><Logo team={c} size={88}/></div><div className="match"><Club name={s.team1} score={s.score1}/><div className="vs">FINAL<br/><b>VS</b></div><Club name={s.team2} score={s.score2}/></div><div className="sbmvp"><Trophy/><div><span>{s.superBowl} MVP</span><strong>{s.superBowlMVP}</strong><small>{s.champion}</small></div></div><h3>Regular Season Awards</h3><div className="awards">{s.awards.map(x=><div className="award" key={x.award}><span>{x.award}</span><Logo team={x.team} size={36}/><div><b>{x.player}</b><small>{names[x.team]||x.team}</small></div></div>)}</div></article>}
function Club({name,score}){return <div className="club"><Logo team={teamCode(name)} size={76}/><b>{name}</b><strong>{score}</strong></div>}
function Tabs({metric,setMetric}){return <div className="tabs">{d.metrics.map(m=><button key={m} className={metric===m?'on':''} onClick={()=>setMetric(m)}>{m}</button>)}</div>}
function Board({title,rows,context}){return <section className="board"><h3>{title}</h3>{rows.slice(0,30).map((r,i)=><div className="row" key={`${r.player}-${i}`}><em>{i+1}</em><span><b>{r.player}</b>{r.context&&<small>{context}: {r.context}</small>}</span><strong>{fmt(r.value)}</strong></div>)}</section>}
function PageTitle({eyebrow='WORKBOOK RECORDS',title,subtitle}){return <div className="pageTitle"><span>{eyebrow}</span><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>}
function App(){const[view,setView]=useState('dashboard'),[team,setTeam]=useState('ARI'),[metric,setMetric]=useState('Pass Yards'),[period,setPeriod]=useState('Career'),[q,setQ]=useState('');const go=x=>{setView(x);scrollTo(0,0)};const teams=useMemo(()=>Object.keys(d.teams).filter(t=>(names[t]||t).toLowerCase().includes(q.toLowerCase())||t.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>(names[a]||a).localeCompare(names[b]||b)),[q]);return <><Header go={go}/><main>{view==='dashboard'&&<Dashboard go={go}/>} {view==='franchises'&&<><PageTitle title="Franchise Records" subtitle="Browse every franchise worksheet in the Madden dynasty."/><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search franchises..."/></div><div className="grid">{teams.map(t=><button key={t} onClick={()=>{setTeam(t);go('team')}}><Logo team={t}/><span><b>{names[t]||t}</b><small>{t} worksheet</small></span><ChevronRight/></button>)}</div></>} {view==='team'&&<><button className="back" onClick={()=>go('franchises')}>← All franchises</button><div className="teamPage"><Logo team={team} size={82}/><PageTitle eyebrow={`${team} WORKBOOK SHEET`} title={names[team]||team}/></div><div className="toggle"><button className={period==='Career'?'on':''} onClick={()=>setPeriod('Career')}>Career</button><button className={period==='Single Season'?'on':''} onClick={()=>setPeriod('Single Season')}>Single Season</button></div><Tabs metric={metric} setMetric={setMetric}/><Board title={`${period} ${metric}`} rows={d.teams[team][period][metric]}/></>} {view==='one'&&<><PageTitle title="One Team Leaders" subtitle="Career production attributed to one franchise in the workbook."/><Tabs metric={metric} setMetric={setMetric}/><Board title={metric} rows={d.oneTeam[metric]} context="Team"/></>} {view==='all'&&<><PageTitle title="All-Time Leaders" subtitle="Overall career totals and year ranges from the All-Time worksheet."/><Tabs metric={metric} setMetric={setMetric}/><Board title={metric} rows={d.allTime[metric]} context="Years"/></>}</main><footer>Statistics are displayed from Stats.xlsx. Team marks belong to their respective rights holders.</footer></>}
createRoot(document.getElementById('root')).render(<App/>);
